site_name: Heureka Docs
site_url: https://mmrqa.github.io/docs/
theme:
  name: material
  features:
    - navigation.instant
    - search.highlight
    - search.smart
    - navigation.sections
    - navigation.indexes
  palette:
    primary: indigo
    accent: blue
nav:
  - Home: 'index.md'
  - Quickstart: 'quickstart'
  - Getting Started:
    - About Heureka: 'getstarted/#about-heureka'
    - Using Heureka: 'getstarted/#using-heureka'
    - Changelog: 'getstarted/#changelog'
  - Check Feasability:
    - Authentification Guide: 'checkfeasability/#authentification-guide'
    - API Usage Guide: 'checkfeasability/#api-usage-guide'
    - Checkliste: 'checkfeasability/#feasability-checklist'
  - Develop Integration:
    - Development Guide: 'developintegration/#development-guide'
    - Legal Guide: 'developintegration/#legal-guide'
    - Checkliste: 'developintegration/#integration-checklist'
  - Deploy Pilot:
    - Publish on Portal: 'deploypilot/#publish-to-portal'
    - Oboarding HCP: 'deploypilot/#onboard-hcp'
    - Checkliste: 'deploypilot/#pilot-checklist'
  - References:
    - API Reference: 'apireference'
    - Fhir Reference: 'fhirreference'
    - FAQ: 'faq'